GET http://localhost:3000/events

### Post Event
# @name createEvent
POST http://localhost:3000/events
Content-Type: application/json

{
    "name": "New time, novos events",
    "description": "This is a new test event",
    "date": "2017-01-01T00:00:00",
    "price": 4000
}

###
@eventId = {{ createEvent.response.body.id }}

### GET EVENT BY ID
GET http://localhost:3000/events/{{eventId}}

### UPDATE EVENT BY ID
PATCH http://localhost:3000/events/{{eventId}}
Content-Type: application/json

{
    "name": "New name",
    "description": "This is a new event updated",
    "date": "2017-01-01T00:00:00",
    "price": 120
}

### REMOVE EVENT BY ID
DELETE http://localhost:3000/events/


### Spots
# @name createSpot

POST http://localhost:3000/events/{{eventId}}/spots
Content-Type: application/json

{
    "name": "Test"
}
