GET http://localhost:3000/events

### Post Event
# @name createEvent
POST http://localhost:3000/events
Content-Type: application/json

{
    "name": "Sexta 27",
    "description": "This is a new test event",
    "date": "2024-01-01T00:00:00",
    "price": 100
}

###
@eventId = {{ createEvent.response.body.id }}

### GET EVENT BY ID
GET http://localhost:3000/events/{{eventId}}

### UPDATE EVENT BY ID
PATCH http://localhost:3000/events/{{eventId}}
Content-Type: application/json

{
    "name": "Sexta 27",
    "description": "This is a new event updated",
    "date": "2024-08-08T00:00:00",
    "price": 120
}

### REMOVE EVENT BY ID
DELETE http://localhost:3000/events/


### Spots
# @name createSpot

POST http://localhost:3000/events/{{eventId}}/spots
Content-Type: application/json

{
    "name": "A3"
}


###
@spotName = {{ createSpot.response.body.name }}

###
POST http://localhost:3000/events/{{eventId}}/reserve
Content-Type: application/json
X-Api-Token: 1234

{
  "spots": ["A3"],
  "ticket_kind": "half",
  "email": "test@test.com"
}