services:
  app:
    build: .
    ports:
      - 3301:3000
    volumes:
      - .:/home/node/app

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mysql:/docker-entrypoint-initdb.d
