services:
  golang-mysql:
    image: mysql:8.0.30-debian
    container_name: golang-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - golang-mysql-data:/var/lib/mysql
    networks:
      - events-network
      - default

  golang:
    build: .
    container_name: golang-api
    ports:
      - "8080:8080"
    depends_on:
      golang-mysql:
        condition: service_healthy
    environment:
      - DB_HOST=golang-mysql
      - DB_PORT=3306
      - DB_USER=test_user
      - DB_PASSWORD=test_password
      - DB_NAME=test_db
    # Volumes removidos para evitar sobrescrever o binário compilado
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - events-network
      - default
    restart: on-failure

volumes:
  golang-mysql-data:

networks:
  events-network:
    driver: bridge